version: '3.8'

services:
  api:
    build:
      context: .
    container_name: go-api
    hostname: go-api
    ports:
      - "3000:5000"
    deploy:
      restart_policy:
        condition: unless-stopped